apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockserver
spec:
  selector:
    matchLabels:
      run: mockserver
  replicas: 1
  template:
    metadata:
      labels:
        run: mockserver
    spec:
      containers:
        - name: mockserver
          image: <your mockserver image name>
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: mockserver
  labels:
    run: mockserver
spec:
  ports:
    - port: 5001
      protocol: TCP
  selector:
    run: mockserver
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mockserver
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: "mockserver.catalyst.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mockserver
                port:
                  number: 5001
