# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lhci-mobile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: run Lighthouse CI
        run: |
          yarn workspace client lhci autorun --config ./lighthouse/lighthouse.mobile.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload Artifacts
          path: |
            .lighthouseci
  lhci-desktop:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: run Lighthouse CI
        run: |
          yarn workspace client lhci autorun --config ./lighthouse/lighthouse.desktop.js
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload Artifacts
          path: |
            .lighthouseci
