# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: Upload production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Static Build folder
          path: |
            ./packages/client/dist
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: Running Tests
        run: yarn workspace client run test
      - run: yarn workspace client run build
      - name: Upload test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            ./packages/client/coverage
      - name: Monitor coverage
        if: github.event_name == 'pull_request'
        uses: slavcodev/coverage-monitor-action@1.2.0
        with:
          github_token: ${{ secrets.GT_TOKEN }}
          clover_file: "./packages/client/coverage/clover.xml"
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn workspace client run build
          start: yarn workspace client run serve
          working-directory: ./packages/e2e/
      - name: Cypress-screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: ./packages/e2e/cypress/screenshots
      - name: Cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: ./packages/e2e/cypress/videos
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
          yarn link-all
          yarn --frozen-lockfile
      - name: Build packages
        run: |
          yarn workspace components build
          yarn workspace client run build
      - name: Running eslint
        run: yarn eslint:check
      - name: Running prettier
        run: yarn prettier:check
      - name: Running stylelint
        run: yarn stylelint:check
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Running audit check
        run: yarn audit
        continue-on-error: true
